# version: '3.8'  # Obsolete - removed to avoid warnings

services:
  govuk_stats_counter:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: uv run
    command: python src/get_count.py
    volumes:
    - ./data:/data
    environment:
     LOGFILE: /data/govuk_stats_log.json

